# Generated by Django 2.1.7 on 2019-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='7f2cd06b-c1a4-43a3-88ff-d0f05537fa7c')),
            ],
        ),
    ]
