# Generated by Django 2.1.7 on 2019-04-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
